export const BESS_COPY: Record<string, string> = {
  _BESS_LIVE: 'Live',
  _BESS_PAUSED: 'Paused',
  _BESS_PAUSE_SIM: 'Pause simulation',
  _BESS_RESUME_SIM: 'Resume simulation',
  _BESS_INVERTERS: 'inverters',
  _BESS_STRINGS: 'strings',
  _BESS_OF: 'of',

  _BESS_SECTION_LIVE: 'Live metrics',
  _BESS_SECTION_LIVE_LEAD: 'Instantaneous plant readings, refreshed as the simulated day advances.',
  _BESS_SECTION_SITE: 'Site conditions',
  _BESS_SECTION_SITE_LEAD: 'Weather driving generation, and where the energy is flowing right now.',
  _BESS_SECTION_STORAGE: 'Battery banks',
  _BESS_SECTION_STORAGE_LEAD: 'State of charge, health and thermal status for each storage bank.',
  _BESS_SECTION_TRENDS: 'Trends',
  _BESS_SECTION_TRENDS_LEAD: 'How generation, storage and grid exchange developed over the simulated day.',
  _BESS_SECTION_EQUIPMENT: 'Equipment',
  _BESS_SECTION_EQUIPMENT_LEAD: 'Per-device telemetry for inverters, DC strings, EV chargers and active alarms.',

  _BESS_KPI_PV: 'PV generation',
  _BESS_KPI_BATTERY: 'Battery power',
  _BESS_KPI_SOC: 'State of charge',
  _BESS_KPI_LOAD: 'Site load',
  _BESS_KPI_GRID: 'Grid exchange',
  _BESS_KPI_YIELD: 'Yield today',
  _BESS_KPI_EV: 'EV charging',
  _BESS_KPI_IMPORT: 'Grid import today',
  _BESS_PEAK: 'Peak',

  _BESS_FLOW_TITLE: 'Energy flow topology',
  _BESS_FLOW_DESC:
    'Single-line diagram with live power on every branch. Animation direction follows the actual direction of energy.',
  _BESS_FLOW_EXPORT: 'Export',
  _BESS_FLOW_IMPORT: 'Import',
  _BESS_FLOW_CHARGE: 'Charging',
  _BESS_FLOW_DISCHARGE: 'Discharging',
  _BESS_NODE_PV: 'PV array',
  _BESS_NODE_INV: 'Inverters',
  _BESS_NODE_BUS: 'AC bus',
  _BESS_NODE_GRID: 'Grid / POI',
  _BESS_NODE_LOAD: 'Site load',
  _BESS_NODE_EV: 'EV charging hub',
  _BESS_IRRADIANCE: 'Irradiance',

  _BESS_CURTAILED: 'Curtailed',
  _BESS_TODAY: 'Today',
  _BESS_SELF_SUFFICIENCY: 'Self-sufficiency',
  _BESS_C_RATE: 'C-rate',

  _BESS_MODE_CHARGING: 'Charging',
  _BESS_MODE_DISCHARGING: 'Discharging',
  _BESS_MODE_IDLE: 'Idle',
  _BESS_POWER: 'Power',
  _BESS_AVAILABLE: 'Available',
  _BESS_CYCLES: 'Cycles',
  _BESS_CELL_TEMP: 'Cell temp.',

  _BESS_CHART_TITLE: '24-hour power and state of charge',
  _BESS_CHART_DESC:
    'Generation, load, battery power and grid exchange over the simulated day. The vertical marker shows the current moment.',
  _BESS_LEGEND_PV: 'PV generation',
  _BESS_LEGEND_LOAD: 'Site load',
  _BESS_LEGEND_EV: 'EV charging',
  _BESS_LEGEND_BATTERY: 'Battery (+ discharge / − charge)',
  _BESS_LEGEND_GRID: 'Grid (+ import / − export)',
  _BESS_LEGEND_SOC: 'State of charge',

  _BESS_TAB_INVERTERS: 'Inverters',
  _BESS_TAB_STRINGS: 'Strings',
  _BESS_TAB_CHARGERS: 'EV chargers',
  _BESS_TAB_ALARMS: 'Alarms',

  _BESS_INV_DESC:
    '18 string inverters rated 100–125 kW, grouped into three blocks. The bar under each card shows load against nameplate rating, the segments below show per-string health.',
  _BESS_STATUS_ONLINE: 'Online',
  _BESS_STATUS_DERATED: 'Derated',
  _BESS_STATUS_FAULT: 'Fault',
  _BESS_STATUS_STANDBY: 'Standby',

  _BESS_STR_DESC:
    'Performance ratio of all 90 DC strings against the block average. Soiling, shading, connector faults and PID show up here long before they hit the monthly yield report.',
  _BESS_STR_GOOD: 'Healthy ≥ 96%',
  _BESS_STR_FAIR: 'Normal 90–96%',
  _BESS_STR_WATCH: 'Watch 80–90%',
  _BESS_STR_POOR: 'Fault < 80%',
  _BESS_STR_DIALOG_SUFFIX: 'DC strings',
  _BESS_STR_DIALOG_DESC: 'Live power, voltage, current and performance ratio for every DC string on this inverter.',
  _BESS_STR_COL_STRING: 'String',
  _BESS_STR_COL_HEALTH: 'Health',
  _BESS_STR_COL_POWER: 'Power',
  _BESS_STR_COL_VOLTAGE: 'Voltage',
  _BESS_STR_COL_CURRENT: 'Current',
  _BESS_STR_COL_RATIO: 'Ratio',
  _BESS_STR_BADGE_GOOD: 'Good',
  _BESS_STR_BADGE_FAIR: 'Fair',
  _BESS_STR_BADGE_WATCH: 'Watch',
  _BESS_STR_BADGE_POOR: 'Poor',
  _BESS_STR_VIEW_DETAILS: 'View string details',
  _BESS_DIALOG_CLOSE: 'Close',

  _BESS_ALARM_DESC: 'Rule-based alarms from inverters, storage banks and the point of interconnection.',
  _BESS_ALARM_SEVERITY: 'Severity',
  _BESS_ALARM_TIME: 'Time',
  _BESS_ALARM_SOURCE: 'Source',
  _BESS_ALARM_MESSAGE: 'Message',
  _BESS_SEV_CRITICAL: 'Critical',
  _BESS_SEV_WARNING: 'Warning',
  _BESS_SEV_INFO: 'Info',
  _BESS_ALARM_M0: 'Active power curtailment at the point of interconnection',
  _BESS_ALARM_M1: 'DC insulation resistance below threshold — inverter offline',
  _BESS_ALARM_M2: 'String current deviation −56% against block average',
  _BESS_ALARM_M3: 'Thermal derating active — output limited to 62%',
  _BESS_ALARM_M4: 'Soiling detected, performance ratio 0.61',
  _BESS_ALARM_M5: 'State of health below 97% — service window recommended',
  _BESS_ALARM_M6: 'Inverter in standby: scheduled maintenance window',
  _BESS_ALARM_M7: 'EV connector locked: cable lock actuator not responding',
  _BESS_ALARM_M8: 'EV hub near rated power — dynamic power sharing engaged',
  _BESS_ALARM_M9: 'Peak shaving active: battery is holding grid import at the 500 kW cap',

  _BESS_EV_STATIONS: 'stations',
  _BESS_EV_CONNECTORS: 'connectors busy',
  _BESS_EV_CONNECTORS_SHORT: 'conn',
  _BESS_EV_GREEN: 'solar',
  _BESS_EV_SESSIONS: 'sessions',
  _BESS_EV_MIN_LEFT: 'min left',
  _BESS_EVSE_CHARGING: 'Charging',
  _BESS_EVSE_IDLE: 'Idle',
  _BESS_EVSE_FAULT: 'Fault',
  _BESS_EVSE_DESC: 'Four DC fast chargers, 160-240 kW each, with per-connector session telemetry and dynamic power sharing.',
  _BESS_VEH_SEDAN: 'Sedan 82 kWh',
  _BESS_VEH_SUV: 'SUV 100 kWh',
  _BESS_VEH_COMPACT: 'Compact 58 kWh',
  _BESS_VEH_VAN: 'Van 110 kWh',
  _BESS_VEH_TRUCK: 'Truck 336 kWh',

  _BESS_WX_TITLE: 'Weather & PV forecast',
  _BESS_WX_DESC: 'Conditions driving irradiance, panel derating and charging demand',
  _BESS_WX_CLOUD: 'Cloud cover',
  _BESS_WX_WIND: 'Wind',
  _BESS_WX_HUMIDITY: 'Humidity',
  _BESS_WX_POTENTIAL: 'PV potential',
  _BESS_WX_FORECAST: 'Next 8 hours',
  _BESS_WX_CLEAR: 'Clear',
  _BESS_WX_PARTLY: 'Partly cloudy',
  _BESS_WX_CLOUDY: 'Cloudy',
  _BESS_WX_OVERCAST: 'Overcast',
  _BESS_WX_RAIN: 'Rain',

  _BESS_GRID_TITLE: 'Grid exchange by hour',
  _BESS_GRID_DESC: '500 kW import connection and 750 kW export limit, metered hour by hour at the interconnection point',
  _BESS_GRID_CHART_TITLE: 'Hourly grid import and export',
  _BESS_GRID_IMPORT_TODAY: 'Imported today',
  _BESS_GRID_EXPORT_TODAY: 'Exported today',
  _BESS_GRID_NET: 'Net balance',
  _BESS_GRID_PEAK_HOUR_IN: 'Busiest hour in',
  _BESS_GRID_PEAK_HOUR_OUT: 'out',
  _BESS_GRID_SHAVED: 'Peak shaved by BESS',
  _BESS_GRID_SHAVED_NOTE: 'Battery covers demand above the 500 kW import cap',
};

export const t = (key: string): string => BESS_COPY[key] ?? key;
